# Generated by Django 5.1.4 on 2025-01-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathrooms', models.FloatField()),
                ('isparking', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rooms', models.FloatField()),
                ('size', models.FloatField()),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField()),
                ('prediction_value', models.FloatField()),
                ('log_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
