# Generated by Django 5.1.4 on 2025-01-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_predictionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='input_features',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
