# Generated by Django 5.1.4 on 2025-01-13 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_predictionhistory_input_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionhistory',
            name='input_features',
        ),
    ]
